apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: te0f698kf-go
  janus-idp.io/tekton: te0f698kf-go
  backstage.io/kubernetes-id: te0f698kf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: te0f698kf-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
